# Generated by Django 5.0 on 2024-01-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('Deposit', 1), ('Borrow', 2), ('Return', 3)]),
        ),
    ]
