# Generated by Django 5.0.1 on 2024-01-03 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pfp', models.URLField(blank=True, choices=[('https://i.pinimg.com/736x/b9/b5/fb/b9b5fbe0ce482fb220303222f70fcac0.jpg', 'https://i.pinimg.com/736x/b9/b5/fb/b9b5fbe0ce482fb220303222f70fcac0.jpg'), ('https://wallpapers.com/images/hd/gojo-chibi-cool-pfp-for-discord-6wf4zioh9pzzw43k.jpg', 'https://wallpapers.com/images/hd/gojo-chibi-cool-pfp-for-discord-6wf4zioh9pzzw43k.jpg'), ('https://wallpapers.com/images/hd/glowing-eyes-for-cool-pfp-for-discord-o01oqgxlvi4t3i4u.jpg', 'https://wallpapers.com/images/hd/glowing-eyes-for-cool-pfp-for-discord-o01oqgxlvi4t3i4u.jpg'), ('https://wallpapers.com/images/hd/pfp-for-discord-cool-ninja-r9f6fiq3bk6d0umy.jpg', 'https://wallpapers.com/images/hd/pfp-for-discord-cool-ninja-r9f6fiq3bk6d0umy.jpg'), ('https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-1024x1024.jpg', 'https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-1024x1024.jpg'), ('https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-for-boys-1024x1024.jpg', 'https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-for-boys-1024x1024.jpg')], default=None, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('borrowed_books', models.ManyToManyField(related_name='books', to='book.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
