# Generated by Django 5.0 on 2024-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userbankaccount_user_useraccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pfp',
            field=models.URLField(blank=True, choices=[('https://i.pinimg.com/736x/b9/b5/fb/b9b5fbe0ce482fb220303222f70fcac0.jpg', 'https://i.pinimg.com/736x/b9/b5/fb/b9b5fbe0ce482fb220303222f70fcac0.jpg'), ('https://wallpapers.com/images/hd/gojo-chibi-cool-pfp-for-discord-6wf4zioh9pzzw43k.jpg', 'https://wallpapers.com/images/hd/gojo-chibi-cool-pfp-for-discord-6wf4zioh9pzzw43k.jpg'), ('https://wallpapers.com/images/hd/glowing-eyes-for-cool-pfp-for-discord-o01oqgxlvi4t3i4u.jpg', 'https://wallpapers.com/images/hd/glowing-eyes-for-cool-pfp-for-discord-o01oqgxlvi4t3i4u.jpg'), ('https://wallpapers.com/images/hd/pfp-for-discord-cool-ninja-r9f6fiq3bk6d0umy.jpg', 'https://wallpapers.com/images/hd/pfp-for-discord-cool-ninja-r9f6fiq3bk6d0umy.jpg'), ('https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-1024x1024.jpg', 'https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-1024x1024.jpg'), ('https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-for-boys-1024x1024.jpg', 'https://kinemasterkingpro.com/wp-content/uploads/2023/11/cool-pfp-for-boys-1024x1024.jpg')], default=None, null=True),
        ),
    ]
