# Generated by Django 5.0 on 2024-01-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_created_on_useraccount_pfp'),
        ('book', '0006_remove_book_language_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='borrowed_books',
            field=models.ManyToManyField(related_name='books', to='book.book'),
        ),
    ]
