# Generated by Django 5.0 on 2024-01-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('isbn', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('pages', models.IntegerField()),
                ('first_published', models.DateField()),
                ('book_type', models.CharField(choices=[('Paperback', 'Paperback'), ('Hard Cover', 'Hard Cover'), ('E-Book', 'E-Book')], max_length=10, verbose_name='type')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
                ('genres', models.ManyToManyField(to='book.category')),
                ('language', models.ManyToManyField(to='book.language')),
            ],
        ),
    ]
