# Generated by Django 5.0.1 on 2024-01-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('isbn', models.IntegerField()),
                ('image', models.URLField()),
                ('pages', models.IntegerField()),
                ('first_published', models.DateField()),
                ('book_type', models.CharField(choices=[('Paperback', 'Paperback'), ('Hard Cover', 'Hard Cover'), ('E-Book', 'E-Book')], max_length=255, verbose_name='type')),
                ('genres', models.ManyToManyField(related_name='genres', to='book.category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.language')),
            ],
        ),
    ]
