# Generated by Django 5.0 on 2024-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('Paperback', 'Paperback'), ('Hard Cover', 'Hard Cover'), ('E-Book', 'E-Book')], max_length=255, verbose_name='type'),
        ),
    ]
