# Generated by Django 5.0 on 2024-01-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userbankaccount_user_useraccount_and_more'),
        ('review', '0002_review_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
        ),
    ]
