# Generated by Django 5.0 on 2023-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
