# Generated by Django 5.0.1 on 2024-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
