# Generated by Django 5.0.1 on 2024-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_discount_price'),
        ('order', '0003_alter_order_placed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='food.food'),
        ),
    ]
