# Generated by Django 5.0.1 on 2024-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_quantity'),
        ('order', '0005_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='orders', to='food.food'),
        ),
    ]
