# Generated by Django 5.0.1 on 2024-01-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='food.food'),
        ),
    ]
