# Generated by Django 5.0.1 on 2024-01-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_cart_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
