# Generated by Django 5.0.1 on 2024-01-15 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraddress_is_default_alter_useraddress_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='name',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
