# Generated by Django 5.0.1 on 2024-01-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_useraddress_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='phone',
        ),
    ]
