# Generated by Django 5.0 on 2024-01-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.URLField()),
                ('is_discount', models.BooleanField()),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
