# Generated by Django 5.0.1 on 2024-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_discount',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
