# Generated by Django 5.0.1 on 2024-01-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_category_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
