# Generated by Django 5.0 on 2024-01-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
    ]
